;;; sherlock-theme.el --- Personal Emacs theme -*- lexical-binding: t; -*-

;;; Commentary:

;;; Code:

(deftheme sherlock
  "A simple Emacs theme based on my vim Sherlock theme, with some additions.")

(let ((main-bg    "#262626")
      (main-fg	  "#ffd7af")
      (dark-bg    "#1f1f1f")
      (light-bg   "#2c2c2c")
      (white      "#fbf8ff")
      (red        "#e06767")
      (red-bg     "#432f2f")
      (green      "#5faf5f")
      (green-bg   "#2c352c")
      (blue       "#87afaf")
      (blue-bg    "#313636")
      (yellow     "#d7af5f")
      (yellow-bg  "#38342c")
      (violet	  "#cdb5cd")
      (cyan       "#87af97")
      (gray-1     "#303030")
      (gray-2     "#404040")
      (gray-3     "#585858")
      (gray-4     "#767676"))

  (custom-theme-set-faces
   'sherlock
   
   ;; Basics
   `(default					((t :background ,main-bg :foreground ,main-fg)))
   `(italic					((t :slant italic)))
   `(fringe					((t :foreground ,green)))
   `(vertical-border				((t :foreground ,dark-bg)))
   `(region					((t :background ,gray-2 :distant-foreground ,gray-3 :extend t)))
   `(cursor					((t :background ,main-fg)))
   `(shadow					((t :foreground ,gray-3)))
   `(minibuffer-prompt				((t :foreground ,blue)))
   `(tooltip					((t :background ,dark-bg :foreground ,main-fg)))
   `(secondary-selection			((t :background ,gray-1 :extend t)))
   `(highlight					((t :background ,blue :foreground ,dark-bg :distant-foreground ,gray-3)))
   `(lazy-highlight				((t :background ,green-bg :foreground ,green :distant-foreground ,dark-bg :weight bold)))
   `(match					((t :foreground ,green :background ,green-bg :weight bold)))
   `(link					((t :foreground ,blue :underline t :weight bold)))
   `(link-visited				((t :inherit link :foreground ,violet)))
   `(error					((t :foreground ,red)))
   `(warning					((t :foreground ,yellow)))
   `(success					((t :foreground ,green)))
   `(hl-line					((t :background ,gray-1 :extend t)))
   `(trailing-whitespace			((t :background ,red)))
   `(escape-glyph				((t :foreground ,white)))
   `(nobreak-space				((t :inherit escape-glyph :underline t)))

   ;; Font lock
   `(font-lock-builtin-face			((t :foreground ,violet)))
   `(font-lock-comment-face			((t :foreground ,gray-3)))
   `(font-lock-comment-delimiter-face		((t :inherit font-lock-comment-face)))
   `(font-lock-doc-face				((t :foreground ,gray-4)))
   `(font-lock-constant-face			((t :foreground ,violet)))
   `(font-lock-function-name-face		((t :foreground ,violet)))
   `(font-lock-function-use-face		((t :foreground ,violet)))
   `(font-lock-keyword-face			((t :foreground ,blue)))
   `(font-lock-string-face			((t :foreground ,red)))
   `(font-lock-type-face			((t :foreground ,yellow)))
   `(font-lock-variable-name-face		((t :foreground ,main-fg)))
   `(font-lock-variable-use-face		((t :foreground ,main-fg)))
   `(font-lock-property-name-face		((t :foreground ,main-fg)))
   `(font-lock-number-face			((t :foreground ,red)))
   `(font-lock-operator-face			((t :foreground ,white)))
   `(font-lock-punctuation-face			((t :foreground ,white)))
   `(font-lock-misc-punctuation-face		((t :foreground ,white)))
   `(font-lock-warning-face			((t :inherit warning)))
   `(font-lock-preprocessor-face		((t :foreground ,blue :weight bold)))
   `(font-lock-preprocessor-char-face		((t :foreground ,blue :weight bold)))
   `(font-lock-regexp-grouping-backslash	((t :foreground ,blue :weight bold)))
   `(font-lock-regexp-grouping-construct	((t :foreground ,blue :weight bold)))
   `(font-lock-negation-char-face		((t :foreground ,blue :weight bold)))
   `(font-lock-escape-face			((t :foreground ,white)))
   `(eglot-highlight-symbol-face		((t :underline t)))
   
   ;; Mode line
   `(mode-line					((t :background ,dark-bg :foreground ,main-fg :box (:line-width 4 :color ,dark-bg))))
   `(mode-line-active				((t :inherit mode-line)))
   `(mode-line-inactive				((t :background ,dark-bg :foreground ,gray-3 :box (:line-width 4 :color ,dark-bg))))
   `(mode-line-emphasis				((t :foreground ,blue)))
   `(mode-line-highlight			((t :inherit highlight :box (:line-width 4 :color ,blue))))
   `(mode-line-buffer-id			((t :weight bold)))
   `(mode-line-git-branch			((t :foreground ,green :slant italic)))
   `(header-line				((t :background ,dark-bg :foreground ,main-fg :box (:line-width 4 :color ,dark-bg))))
   
   ;; Search & Completion
   `(icomplete-selected-match			((t :foreground ,main-fg :background ,dark-bg :box (:line-width (4 . 2) :color ,dark-bg))))
   `(icomplete-first-match			((t :weight regular :foreground ,yellow)))
   `(completions-common-part			((t :foreground ,blue)))
   `(completions-first-difference		((t :foreground ,yellow)))
   `(completion-preview-exact			((t :inherit completion-preview-common)))
   `(isearch					((t :inherit lazy-highlight :weight bold)))
   `(isearch-fail				((t :background ,red :foreground ,dark-bg :weight bold)))
   
   ;; Bracket matching
   `(show-paren-match				((t :foreground ,blue :background ,blue-bg :weight bold)))
   `(show-paren-mismatch			((t :foreground ,red :background ,red-bg :weight bold)))
   
   ;; Flymake
   `(flymake-error				((t :underline (:style wave :color ,red))))
   `(flymake-note				((t :underline (:style wave :color ,green))))
   `(flymake-warning				((t :underline (:style wave :color ,yellow))))
   `(flyspell-incorrect 			((t :underline (:style wave :color ,red) :inherit nil)))
   `(flyspell-duplicate 			((t :underline (:style wave :color ,yellow) :inherit nil)))
   
   ;; UI
   `(custom-button				((t :foreground ,blue :background ,main-bg :box (:line-width 1))))
   `(custom-button-unraised			((t :foreground ,violet :background ,main-bg :box (:line-width 1))))
   `(custom-button-pressed-unraised		((t :foreground ,main-bg :background ,violet :box (:line-width 1))))
   `(custom-button-pressed			((t :foreground ,main-bg :background ,blue :box (:line-width 1))))
   `(custom-button-mouse			((t :foreground ,main-bg :background ,blue :box (:line-width 1))))
   `(custom-variable-button			((t :foreground ,green :underline t)))
   `(custom-saved				((t :foreground ,green :background ,green-bg :bold t)))
   `(custom-comment				((t :foreground ,main-fg :background ,gray-1)))
   `(custom-comment-tag				((t :foreground ,gray-2)))
   `(custom-modified				((t :foreground ,blue :background ,blue-bg)))
   `(custom-variable-tag			((t :foreground ,violet)))
   `(custom-visibility				((t :foreground ,blue)))
   `(custom-group-subtitle			((t :foreground ,red)))
   `(custom-group-tag				((t :foreground ,violet)))
   `(custom-group-tag-1				((t :foreground ,blue)))
   `(custom-set					((t :foreground ,yellow :background ,main-bg)))
   `(custom-themed				((t :foreground ,yellow :background ,main-bg)))
   `(custom-invalid				((t :foreground ,red :background ,red-bg)))
   `(custom-variable-obsolete			((t :foreground ,gray-2 :background ,main-bg)))
   `(custom-state				((t :foreground ,green :background ,green-bg)))
   `(custom-changed				((t :foreground ,blue :background ,main-bg)))
   `(widget-field				((t :background ,dark-bg :extend t :box (:line-width 1 :color ,dark-bg))))
   `(widget-single-line-field			((t :background ,dark-bg)))
   `(Info-quoted				((t :foreground ,violet)))
   `(help-key-binding				((t :foreground ,yellow :background ,dark-bg :box (:line-width 1 :color ,gray-3))))
   `(tutorial-warning-face			((t :foreground ,red)))
   `(info-menu-star				((t :foreground ,violet)))
   
   ;; Dired
   `(dired-directory				((t :foreground ,blue)))
   `(dired-ignored				((t :foreground ,gray-3)))
   `(dired-flagged				((t :foreground ,red)))
   `(dired-header				((t :foreground ,blue :weight bold)))
   `(dired-mark					((t :foreground ,green)))
   `(dired-marked				((t :foreground ,yellow :weight bold)))
   `(dired-perm-write				((t :foreground ,main-fg :underline t)))
   `(dired-symlink				((t :inherit shadow)))
   `(dired-broken-symlink			((t :inherit show-paren-mismatch)))
   `(dired-warning				((t :inherit warning)))

   ;; Eshell
   `(eshell-prompt				((t :foreground ,yellow :weight bold)))
   `(eshell-ls-archive				((t :foreground ,violet)))
   `(eshell-ls-clutter				((t :foreground ,red)))
   `(eshell-ls-directory			((t :foreground ,blue)))
   `(eshell-ls-executable			((t :foreground ,green)))
   `(eshell-ls-missing				((t :foreground ,red)))
   `(eshell-ls-product				((t :foreground ,red)))
   `(eshell-ls-readonly				((t :foreground ,red)))
   `(eshell-ls-special				((t :foreground ,violet)))
   `(eshell-ls-backup				((t :inherit shadow)))
   `(eshell-ls-symlink				((t :inherit shadow)))
   `(eshell-ls-unreadable			((t :inherit shadow)))

   ;; Speedbar
   `(speedbar-button-face			((t :inherit shadow)))
   `(speedbar-directory-face			((t :inherit dired-directory)))
   `(speedbar-file-face				((t :inherit default)))
   `(speedbar-highlight-face			((t :inherit highlight)))
   `(speedbar-selected-face			((t :inherit dired-marked)))
   `(speedbar-tag-face				((t :foreground ,yellow)))

   ;; Diff
   `(diff-hl-insert				((t :foreground ,green :background ,green)))
   `(diff-hl-change				((t :foreground ,red :background ,red)))
   `(diff-hl-delete				((t :foreground ,red :background ,red)))
   `(diff-indicator-added			((t :foreground ,green :background ,main-bg)))
   `(diff-indicator-changed			((t :foreground ,red :background ,main-bg)))
   `(diff-indicator-removed			((t :foreground ,red :background ,main-bg)))
   `(diff-added					((t :foreground ,green :background ,main-bg)))
   `(diff-changed				((t :foreground ,red :background ,main-bg)))
   `(diff-removed				((t :foreground ,red :background ,main-bg)))
   `(diff-header				((t :foreground ,gray-4)))
   `(diff-file-header				((t :foreground ,gray-4)))
   `(diff-hunk-header				((t :foreground ,blue)))
   `(diff-refine-added				((t :inherit diff-added)))
   `(diff-refine-changed			((t :inherit diff-changed)))
   `(diff-refine-removed			((t :inherit diff-removed)))

   ;; Compilation
   `(compilation-column-number			((t :inherit font-lock-comment-face)))
   `(compilation-line-number			((t :foreground ,blue)))
   `(compilation-error				((t :inherit error :weight bold)))
   `(compilation-warning			((t :inherit warning :slant italic)))
   `(compilation-info				((t :inherit success)))
   `(compilation-mode-line-exit 		((t :inherit compilation-info)))
   `(compilation-mode-line-fail 		((t :inherit compilation-error)))

   ;; TeX errors
   `(TeX-error-description-error		((t :inherit error :weight bold)))
   `(TeX-error-description-warning		((t :inherit warning :slant italic)))
   `(TeX-error-description-tex-said		((t :inherit success)))

   ;; Outline (org headers etc.)
   `(outline-1 					((t :foreground ,blue :weight bold :height 1.3 :extend t)))
   `(outline-2 					((t :foreground ,violet :weight bold :height 1.2 :extend t)))
   `(outline-3 					((t :foreground ,cyan :weight bold :height 1.1 :extend t)))
   `(outline-4 					((t :foreground ,yellow :weight bold :extend t)))
   `(outline-5 					((t :foreground ,blue :weight bold :extend t)))
   `(outline-6 					((t :foreground ,violet :weight bold :extend t)))
   `(outline-7 					((t :foreground ,cyan :weight bold :extend t)))
   `(outline-8 					((t :foreground ,yellow :weight bold :extend t)))

   ;; Org
   `(org-document-info				((t :foreground ,violet)))
   `(org-document-title				((t :foreground ,yellow :weight bold)))
   `(org-date					((t :foreground ,yellow)))
   `(org-block					((t :background ,light-bg :extend t :box (:line-width (10 . -1) :color ,light-bg))))
   `(org-block-background			((t :background ,light-bg :extend t)))
   `(org-block-begin-line			((t :inherit org-block :foreground ,gray-4 :box (:line-width (10 . 4) :color ,light-bg))))
   `(org-block-end-line				((t :inherit org-block-begin-line)))
   `(org-code					((t :inherit org-block :foreground ,red)))
   `(org-verbatim				((t :foreground ,green)))
   `(org-warning				((t :foreground ,yellow)))
   `(org-quote					((t :inherit org-block :slant italic)))
   `(org-cite					((t :foreground ,gray-4)))
   `(org-cite-key				((t :foreground ,yellow)))
   `(org-todo					((t :foreground ,yellow :weight bold)))
   `(org-headline-done				((t :foreground ,gray-3)))
   `(org-done					((t :inherit org-headline-done :weight bold)))
   `(org-priority				((t :foreground ,red)))
   `(org-checkbox				((t :inherit org-todo)))
   `(org-checkbox-statistics-done		((t :inherit org-done)))
   `(org-checkbox-statistics-todo		((t :inherit org-todo)))
   `(org-drawer					((t :inherit shadow)))
   `(org-ellipsis				((t :foreground ,gray-3)))
   `(org-table					((t :foreground ,violet :background ,main-bg :box (:line-width (10 . -1) :color ,main-bg))))
   `(org-formula				((t :foreground ,white)))
   `(org-footnote				((t :foreground ,red)))
   `(org-hide					((t :foreground ,main-bg)))
   `(org-latex-and-related			((t :foreground ,gray-3 :weight bold)))
   `(org-link					((t :inherit link)))
   `(org-list-dt				((t :foreground ,yellow)))
   `(org-meta-line				((t :inherit shadow)))
   `(org-property-value				((t :inherit shadow)))
   `(org-special-keyword			((t :inherit shadow)))
   `(org-tag					((t :inherit shadow)))
   `(org-archived				((t :inherit shadow)))

   ;; Gnus etc.
   `(message-cited-text				((t :foreground ,violet)))
   `(message-cited-text-1			((t :foreground ,yellow)))
   `(message-cited-text-2			((t :foreground ,violet)))
   `(message-cited-text-3			((t :foreground ,green)))
   `(message-cited-text-4			((t :foreground ,green)))
   `(message-header-name			((t :foreground ,violet)))
   `(message-header-to				((t :foreground ,green)))
   `(message-header-cc				((t :foreground ,green)))
   `(message-header-subject			((t :foreground ,yellow)))
   `(message-header-other			((t :foreground ,blue)))
   `(message-separator				((t :foreground ,gray-2)))
   `(message-signature-separator		((t :foreground ,gray-2))))

  (add-hook 'prog-mode-hook
	    (lambda ()
	      (font-lock-add-keywords nil
				      '(("\\<\\(FIXME\\)" 1 'error prepend)
					("\\<\\(TODO\\)" 1 'warning prepend)
					("\\<\\(NOTE\\)" 1 'success prepend))))))

(provide-theme 'sherlock)
(provide 'sherlock-theme)

;;; sherlock-theme.el ends here
