(deftheme watson
  "Inspired by Doom One / Atom One Dark.")

(custom-theme-set-faces
 'watson
 '(bold ((((class color) (min-colors 257)) (:weight bold :foreground unspecified)) (((class color) (min-colors 256)) (:weight bold :foreground unspecified)) (((class color) (min-colors 16)) (:weight bold :foreground unspecified))))
 '(bold-italic ((t (:inherit (bold italic)))))
 '(italic ((t (:slant italic))))
 '(escape-glyph ((((class color) (min-colors 257)) (:foreground "#46D9FF")) (((class color) (min-colors 256)) (:foreground "#46D9FF")) (((class color) (min-colors 16)) (:foreground "brightcyan"))))
 '(fringe ((((class color) (min-colors 257)) (:inherit default :foreground "#3f444a")) (((class color) (min-colors 256)) (:inherit default :foreground "#3f3f3f")) (((class color) (min-colors 16)) (:inherit default :foreground "brightblack"))))
 '(region ((((class color) (min-colors 257)) (:background "#42444a" :distant-foreground "#959ba5" :extend t)) (((class color) (min-colors 256)) (:background "#6c6c6c" :distant-foreground "#989898" :extend t)) (((class color) (min-colors 16)) (:background "brightblack" :distant-foreground "brightwhite" :extend t))))
 '(highlight ((((class color) (min-colors 257)) (:background "#51afef" :foreground "#1B2229" :distant-foreground "#DFDFDF")) (((class color) (min-colors 256)) (:background "#51afef" :foreground "black" :distant-foreground "#dfdfdf")) (((class color) (min-colors 16)) (:background "brightblue" :foreground "black" :distant-foreground "white"))))
 '(cursor ((((class color) (min-colors 257)) (:background "#51afef")) (((class color) (min-colors 256)) (:background "#51afef")) (((class color) (min-colors 16)) (:background "brightblue"))))
 '(shadow ((((class color) (min-colors 257)) (:foreground "#5B6268")) (((class color) (min-colors 256)) (:foreground "#525252")) (((class color) (min-colors 16)) (:foreground "brightblack"))))
 '(minibuffer-prompt ((((class color) (min-colors 257)) (:foreground "#51afef")) (((class color) (min-colors 256)) (:foreground "#51afef")) (((class color) (min-colors 16)) (:foreground "brightblue"))))
 '(tooltip ((((class color) (min-colors 257)) (:background "#21242b" :foreground "#bbc2cf")) (((class color) (min-colors 256)) (:background "black" :foreground "#bfbfbf")) (((class color) (min-colors 16)) (:background "black" :foreground "brightwhite"))))
 '(secondary-selection ((((class color) (min-colors 257)) (:background "#3f444a" :extend t)) (((class color) (min-colors 256)) (:background "#3f3f3f" :extend t)) (((class color) (min-colors 16)) (:background "brightblack" :extend t))))
 '(lazy-highlight ((t (:background "#3e493d" :distant-foreground "#1B2229" :foreground "#98be65" :weight bold))))
 '(match ((((class color) (min-colors 257)) (:foreground "#98be65" :background "#1B2229" :weight bold)) (((class color) (min-colors 256)) (:foreground "#99bb66" :background "black" :weight bold)) (((class color) (min-colors 16)) (:foreground "green" :background "black" :weight bold))))
 '(trailing-whitespace ((((class color) (min-colors 257)) (:background "#ff6c6b")) (((class color) (min-colors 256)) (:background "#ff6655")) (((class color) (min-colors 16)) (:background "red"))))
 '(nobreak-space ((t (:inherit escape-glyph :underline t))))
 '(vertical-border ((((class color) (min-colors 257)) (:background "#191b20" :foreground "#191b20")) (((class color) (min-colors 256)) (:background "#1b1b1b" :foreground "#1b1b1b")) (((class color) (min-colors 16)) (:background "brightblack" :foreground "brightblack"))))
 '(link ((((class color) (min-colors 257)) (:foreground "#51afef" :underline t :weight bold)) (((class color) (min-colors 256)) (:foreground "#51afef" :underline t :weight bold)) (((class color) (min-colors 16)) (:foreground "brightblue" :underline t :weight bold))))
 '(error ((((class color) (min-colors 257)) (:foreground "#ff6c6b")) (((class color) (min-colors 256)) (:foreground "#ff6655")) (((class color) (min-colors 16)) (:foreground "red"))))
 '(warning ((((class color) (min-colors 257)) (:foreground "#ECBE7B")) (((class color) (min-colors 256)) (:foreground "#ECBE7B")) (((class color) (min-colors 16)) (:foreground "yellow"))))
 '(success ((((class color) (min-colors 257)) (:foreground "#98be65")) (((class color) (min-colors 256)) (:foreground "#99bb66")) (((class color) (min-colors 16)) (:foreground "green"))))
 '(font-lock-builtin-face ((((class color) (min-colors 257)) (:foreground "#c678dd")) (((class color) (min-colors 256)) (:foreground "#c678dd")) (((class color) (min-colors 16)) (:foreground "brightmagenta"))))
 '(font-lock-comment-face ((((class color) (min-colors 257)) (:foreground "#5B6268" :background unspecified)) (((class color) (min-colors 256)) (:foreground "#525252" :background unspecified)) (((class color) (min-colors 16)) (:foreground "brightblack" :background unspecified))))
 '(font-lock-comment-delimiter-face ((t (:inherit font-lock-comment-face))))
 '(font-lock-doc-face ((((class color) (min-colors 257)) (:inherit font-lock-comment-face :foreground "#83898d")) (((class color) (min-colors 256)) (:inherit font-lock-comment-face :foreground "#7d7d7d")) (((class color) (min-colors 16)) (:inherit font-lock-comment-face :foreground "brightblack"))))
 '(font-lock-constant-face ((((class color) (min-colors 257)) (:foreground "#a9a1e1")) (((class color) (min-colors 256)) (:foreground "#a9a1e1")) (((class color) (min-colors 16)) (:foreground "magenta"))))
 '(font-lock-function-name-face ((((class color) (min-colors 257)) (:foreground "#c678dd")) (((class color) (min-colors 256)) (:foreground "#c678dd")) (((class color) (min-colors 16)) (:foreground "brightmagenta"))))
 '(font-lock-keyword-face ((((class color) (min-colors 257)) (:foreground "#51afef")) (((class color) (min-colors 256)) (:foreground "#51afef")) (((class color) (min-colors 16)) (:foreground "brightblue"))))
 '(font-lock-string-face ((((class color) (min-colors 257)) (:foreground "#98be65")) (((class color) (min-colors 256)) (:foreground "#99bb66")) (((class color) (min-colors 16)) (:foreground "green"))))
 '(font-lock-type-face ((((class color) (min-colors 257)) (:foreground "#ECBE7B")) (((class color) (min-colors 256)) (:foreground "#ECBE7B")) (((class color) (min-colors 16)) (:foreground "yellow"))))
 '(font-lock-variable-name-face ((((class color) (min-colors 257)) (:foreground "#dcaeea")) (((class color) (min-colors 256)) (:foreground "#dcaeea")) (((class color) (min-colors 16)) (:foreground "brightmagenta"))))
 '(font-lock-number-face ((((class color) (min-colors 257)) (:foreground "#da8548")) (((class color) (min-colors 256)) (:foreground "#dd8844")) (((class color) (min-colors 16)) (:foreground "brightred"))))
 '(font-lock-warning-face ((t (:inherit warning))))
 '(font-lock-negation-char-face ((((class color) (min-colors 257)) (:inherit bold :foreground "#51afef")) (((class color) (min-colors 256)) (:inherit bold :foreground "#51afef")) (((class color) (min-colors 16)) (:inherit bold :foreground "brightblue"))))
 '(font-lock-preprocessor-face ((((class color) (min-colors 257)) (:inherit bold :foreground "#51afef")) (((class color) (min-colors 256)) (:inherit bold :foreground "#51afef")) (((class color) (min-colors 16)) (:inherit bold :foreground "brightblue"))))
 '(font-lock-preprocessor-char-face ((((class color) (min-colors 257)) (:inherit bold :foreground "#51afef")) (((class color) (min-colors 256)) (:inherit bold :foreground "#51afef")) (((class color) (min-colors 16)) (:inherit bold :foreground "brightblue"))))
 '(font-lock-regexp-grouping-backslash ((((class color) (min-colors 257)) (:inherit bold :foreground "#51afef")) (((class color) (min-colors 256)) (:inherit bold :foreground "#51afef")) (((class color) (min-colors 16)) (:inherit bold :foreground "brightblue"))))
 '(font-lock-regexp-grouping-construct ((((class color) (min-colors 257)) (:inherit bold :foreground "#51afef")) (((class color) (min-colors 256)) (:inherit bold :foreground "#51afef")) (((class color) (min-colors 16)) (:inherit bold :foreground "brightblue"))))
 '(mode-line ((((class color) (min-colors 257)) (:background "#1d2026" :foreground "#bbc2cf" :box nil)) (((class color) (min-colors 256)) (:background "black" :foreground "#bfbfbf" :box nil)) (((class color) (min-colors 16)) (:background "black" :foreground "brightwhite" :box nil))))
 '(mode-line-active ((t (:inherit mode-line))))
 '(mode-line-inactive ((((class color) (min-colors 257)) (:background "#21242b" :foreground "#5B6268" :box nil)) (((class color) (min-colors 256)) (:background "#1e1e1e" :foreground "#525252" :box nil)) (((class color) (min-colors 16)) (:background "brightblack" :foreground "brightblack" :box nil))))
 '(mode-line-emphasis ((((class color) (min-colors 257)) (:foreground "#51afef")) (((class color) (min-colors 256)) (:foreground "#51afef")) (((class color) (min-colors 16)) (:foreground "brightblue"))))
 '(mode-line-highlight ((((class color) (min-colors 257)) (:inherit highlight :distant-foreground "#282c34")) (((class color) (min-colors 256)) (:inherit highlight :distant-foreground "black")) (((class color) (min-colors 16)) (:inherit highlight :distant-foreground "black"))))
 '(mode-line-buffer-id ((t (:weight bold))))
 '(header-line ((t (:inherit mode-line))))
 '(header-line-highlight ((t (:inherit mode-line-highlight))))
 '(line-number ((((class color) (min-colors 257)) (:inherit default :foreground "#3f444a" :distant-foreground unspecified :weight normal :italic unspecified :underline unspecified :strike-through unspecified)) (((class color) (min-colors 256)) (:inherit default :foreground "#3f3f3f" :distant-foreground unspecified :weight normal :italic unspecified :underline unspecified :strike-through unspecified)) (((class color) (min-colors 16)) (:inherit default :foreground "brightblack" :distant-foreground unspecified :weight normal :italic unspecified :underline unspecified :strike-through unspecified))))
 '(line-number-current-line ((((class color) (min-colors 257)) (:inherit (hl-line default) :foreground "#bbc2cf" :distant-foreground unspecified :weight normal :italic unspecified :underline unspecified :strike-through unspecified)) (((class color) (min-colors 256)) (:inherit (hl-line default) :foreground "#bfbfbf" :distant-foreground unspecified :weight normal :italic unspecified :underline unspecified :strike-through unspecified)) (((class color) (min-colors 16)) (:inherit (hl-line default) :foreground "brightwhite" :distant-foreground unspecified :weight normal :italic unspecified :underline unspecified :strike-through unspecified))))
 '(font-latex-bold-face ((t (:inherit bold))))
 '(font-latex-italic-face ((t (:inherit italic))))
 '(font-latex-math-face ((((class color) (min-colors 257)) (:foreground "#98be65")) (((class color) (min-colors 256)) (:foreground "#99bb66")) (((class color) (min-colors 16)) (:foreground "green"))))
 '(font-latex-sectioning-0-face ((((class color) (min-colors 257)) (:foreground "#51afef" :weight ultra-bold)) (((class color) (min-colors 256)) (:foreground "#51afef" :weight ultra-bold)) (((class color) (min-colors 16)) (:foreground "brightblue" :weight ultra-bold))))
 '(font-latex-sectioning-1-face ((((class color) (min-colors 257)) (:foreground "#c678dd" :weight semi-bold)) (((class color) (min-colors 256)) (:foreground "#c678dd" :weight semi-bold)) (((class color) (min-colors 16)) (:foreground "brightmagenta" :weight semi-bold))))
 '(font-latex-sectioning-2-face ((((class color) (min-colors 257)) (:foreground "#a9a1e1" :weight semi-bold)) (((class color) (min-colors 256)) (:foreground "#a9a1e1" :weight semi-bold)) (((class color) (min-colors 16)) (:foreground "magenta" :weight semi-bold))))
 '(font-latex-sectioning-3-face ((((class color) (min-colors 257)) (:foreground "#85c7f3" :weight semi-bold)) (((class color) (min-colors 256)) (:foreground "#85c7f3" :weight semi-bold)) (((class color) (min-colors 16)) (:foreground "brightblue" :weight semi-bold))))
 '(font-latex-sectioning-4-face ((((class color) (min-colors 257)) (:foreground "#d7a0e7" :weight semi-bold)) (((class color) (min-colors 256)) (:foreground "#d7a0e7" :weight semi-bold)) (((class color) (min-colors 16)) (:foreground "brightmagenta" :weight semi-bold))))
 '(font-latex-sectioning-5-face ((((class color) (min-colors 257)) (:foreground "#c2bdea" :weight semi-bold)) (((class color) (min-colors 256)) (:foreground "#c2bdea" :weight semi-bold)) (((class color) (min-colors 16)) (:foreground "magenta" :weight semi-bold))))
 '(font-latex-script-char-face ((((class color) (min-colors 257)) (:foreground "#2257A0")) (((class color) (min-colors 256)) (:foreground "#2257A0")) (((class color) (min-colors 16)) (:foreground "blue"))))
 '(font-latex-string-face ((t (:inherit font-lock-string-face))))
 '(font-latex-warning-face ((t (:inherit font-lock-warning-face))))
 '(font-latex-verbatim-face ((((class color) (min-colors 257)) (:inherit fixed-pitch :foreground "#a9a1e1" :slant italic)) (((class color) (min-colors 256)) (:inherit fixed-pitch :foreground "#a9a1e1" :slant italic)) (((class color) (min-colors 16)) (:inherit fixed-pitch :foreground "magenta" :slant italic))))
 '(TeX-error-description-error ((t (:inherit error :weight bold))))
 '(TeX-error-description-warning ((t (:inherit warning :weight bold))))
 '(TeX-error-description-tex-said ((t (:inherit success :weight bold))))
 '(ansi-color-black ((((class color) (min-colors 257)) (:foreground "#282c34" :background "#282c34")) (((class color) (min-colors 256)) (:foreground "black" :background "black")) (((class color) (min-colors 16)) (:foreground "black" :background "black"))))
 '(ansi-color-red ((((class color) (min-colors 257)) (:foreground "#ff6c6b" :background "#ff6c6b")) (((class color) (min-colors 256)) (:foreground "#ff6655" :background "#ff6655")) (((class color) (min-colors 16)) (:foreground "red" :background "red"))))
 '(ansi-color-green ((((class color) (min-colors 257)) (:foreground "#98be65" :background "#98be65")) (((class color) (min-colors 256)) (:foreground "#99bb66" :background "#99bb66")) (((class color) (min-colors 16)) (:foreground "green" :background "green"))))
 '(ansi-color-yellow ((((class color) (min-colors 257)) (:foreground "#ECBE7B" :background "#ECBE7B")) (((class color) (min-colors 256)) (:foreground "#ECBE7B" :background "#ECBE7B")) (((class color) (min-colors 16)) (:foreground "yellow" :background "yellow"))))
 '(ansi-color-blue ((((class color) (min-colors 257)) (:foreground "#51afef" :background "#51afef")) (((class color) (min-colors 256)) (:foreground "#51afef" :background "#51afef")) (((class color) (min-colors 16)) (:foreground "brightblue" :background "brightblue"))))
 '(ansi-color-magenta ((((class color) (min-colors 257)) (:foreground "#c678dd" :background "#c678dd")) (((class color) (min-colors 256)) (:foreground "#c678dd" :background "#c678dd")) (((class color) (min-colors 16)) (:foreground "brightmagenta" :background "brightmagenta"))))
 '(ansi-color-cyan ((((class color) (min-colors 257)) (:foreground "#46D9FF" :background "#46D9FF")) (((class color) (min-colors 256)) (:foreground "#46D9FF" :background "#46D9FF")) (((class color) (min-colors 16)) (:foreground "brightcyan" :background "brightcyan"))))
 '(ansi-color-white ((((class color) (min-colors 257)) (:foreground "#bbc2cf" :background "#bbc2cf")) (((class color) (min-colors 256)) (:foreground "#bfbfbf" :background "#bfbfbf")) (((class color) (min-colors 16)) (:foreground "brightwhite" :background "brightwhite"))))
 '(ansi-color-bright-black ((((class color) (min-colors 257)) (:foreground "#1B2229" :background "#202328")) (((class color) (min-colors 256)) (:foreground "black" :background "#2e2e2e")) (((class color) (min-colors 16)) (:foreground "black" :background "brightblack"))))
 '(ansi-color-bright-red ((((class color) (min-colors 257)) (:foreground "#ff8281" :background "#ff8281")) (((class color) (min-colors 256)) (:foreground "#ff7c6e" :background "#ff7c6e")) (((class color) (min-colors 16)) (:foreground "red" :background "red"))))
 '(ansi-color-bright-green ((((class color) (min-colors 257)) (:foreground "#a7c77c" :background "#a7c77c")) (((class color) (min-colors 256)) (:foreground "#a8c57c" :background "#a8c57c")) (((class color) (min-colors 16)) (:foreground "green" :background "green"))))
 '(ansi-color-bright-yellow ((((class color) (min-colors 257)) (:foreground "#eec78e" :background "#eec78e")) (((class color) (min-colors 256)) (:foreground "#eec78e" :background "#eec78e")) (((class color) (min-colors 16)) (:foreground "yellow" :background "yellow"))))
 '(ansi-color-bright-blue ((((class color) (min-colors 257)) (:foreground "#6bbbf1" :background "#6bbbf1")) (((class color) (min-colors 256)) (:foreground "#6bbbf1" :background "#6bbbf1")) (((class color) (min-colors 16)) (:foreground "brightblue" :background "brightblue"))))
 '(ansi-color-bright-magenta ((((class color) (min-colors 257)) (:foreground "#ce8ce2" :background "#ce8ce2")) (((class color) (min-colors 256)) (:foreground "#ce8ce2" :background "#ce8ce2")) (((class color) (min-colors 16)) (:foreground "brightmagenta" :background "brightmagenta"))))
 '(ansi-color-bright-cyan ((((class color) (min-colors 257)) (:foreground "#61deff" :background "#61deff")) (((class color) (min-colors 256)) (:foreground "#61deff" :background "#61deff")) (((class color) (min-colors 16)) (:foreground "brightcyan" :background "brightcyan"))))
 '(ansi-color-bright-white ((((class color) (min-colors 257)) (:foreground "#DFDFDF" :background "#DFDFDF")) (((class color) (min-colors 256)) (:foreground "#dfdfdf" :background "#dfdfdf")) (((class color) (min-colors 16)) (:foreground "white" :background "white"))))
 '(compilation-column-number ((t (:inherit font-lock-comment-face))))
 '(compilation-line-number ((((class color) (min-colors 257)) (:foreground "#51afef")) (((class color) (min-colors 256)) (:foreground "#51afef")) (((class color) (min-colors 16)) (:foreground "brightblue"))))
 '(compilation-error ((t (:inherit error :weight bold))))
 '(compilation-warning ((t (:inherit warning :slant italic))))
 '(compilation-info ((t (:inherit success))))
 '(compilation-mode-line-exit ((t (:inherit compilation-info))))
 '(compilation-mode-line-fail ((t (:inherit compilation-error))))
 '(custom-button ((((class color) (min-colors 257)) (:foreground "#51afef" :background "#282c34" :box (:line-width 1 :style nil))) (((class color) (min-colors 256)) (:foreground "#51afef" :background "black" :box (:line-width 1 :style nil))) (((class color) (min-colors 16)) (:foreground "brightblue" :background "black" :box (:line-width 1 :style nil)))))
 '(custom-button-unraised ((((class color) (min-colors 257)) (:foreground "#a9a1e1" :background "#282c34" :box (:line-width 1 :style nil))) (((class color) (min-colors 256)) (:foreground "#a9a1e1" :background "black" :box (:line-width 1 :style nil))) (((class color) (min-colors 16)) (:foreground "magenta" :background "black" :box (:line-width 1 :style nil)))))
 '(custom-button-pressed-unraised ((((class color) (min-colors 257)) (:foreground "#282c34" :background "#a9a1e1" :box (:line-width 1 :style nil))) (((class color) (min-colors 256)) (:foreground "black" :background "#a9a1e1" :box (:line-width 1 :style nil))) (((class color) (min-colors 16)) (:foreground "black" :background "magenta" :box (:line-width 1 :style nil)))))
 '(custom-button-pressed ((((class color) (min-colors 257)) (:foreground "#282c34" :background "#51afef" :box (:line-width 1 :style nil))) (((class color) (min-colors 256)) (:foreground "black" :background "#51afef" :box (:line-width 1 :style nil))) (((class color) (min-colors 16)) (:foreground "black" :background "brightblue" :box (:line-width 1 :style nil)))))
 '(custom-button-mouse ((((class color) (min-colors 257)) (:foreground "#282c34" :background "#51afef" :box (:line-width 1 :style nil))) (((class color) (min-colors 256)) (:foreground "black" :background "#51afef" :box (:line-width 1 :style nil))) (((class color) (min-colors 16)) (:foreground "black" :background "brightblue" :box (:line-width 1 :style nil)))))
 '(custom-variable-button ((((class color) (min-colors 257)) (:foreground "#98be65" :underline t)) (((class color) (min-colors 256)) (:foreground "#99bb66" :underline t)) (((class color) (min-colors 16)) (:foreground "green" :underline t))))
 '(custom-saved ((((class color) (min-colors 257)) (:foreground "#98be65" :background "#3e493d" :bold t)) (((class color) (min-colors 256)) (:foreground "#99bb66" :background "#99bb66" :bold t)) (((class color) (min-colors 16)) (:foreground "green" :background "green" :bold t))))
 '(custom-comment ((((class color) (min-colors 257)) (:foreground "#bbc2cf" :background "#42444a")) (((class color) (min-colors 256)) (:foreground "#bfbfbf" :background "#6c6c6c")) (((class color) (min-colors 16)) (:foreground "brightwhite" :background "brightblack"))))
 '(custom-comment-tag ((((class color) (min-colors 257)) (:foreground "#3f444a")) (((class color) (min-colors 256)) (:foreground "#3f3f3f")) (((class color) (min-colors 16)) (:foreground "brightblack"))))
 '(custom-modified ((((class color) (min-colors 257)) (:foreground "#51afef" :background "#304659")) (((class color) (min-colors 256)) (:foreground "#51afef" :background "#51afef")) (((class color) (min-colors 16)) (:foreground "brightblue" :background "brightblue"))))
 '(custom-variable-tag ((((class color) (min-colors 257)) (:foreground "#c678dd")) (((class color) (min-colors 256)) (:foreground "#c678dd")) (((class color) (min-colors 16)) (:foreground "brightmagenta"))))
 '(custom-visibility ((((class color) (min-colors 257)) (:foreground "#51afef" :underline unspecified)) (((class color) (min-colors 256)) (:foreground "#51afef" :underline unspecified)) (((class color) (min-colors 16)) (:foreground "brightblue" :underline unspecified))))
 '(custom-group-subtitle ((((class color) (min-colors 257)) (:foreground "#ff6c6b")) (((class color) (min-colors 256)) (:foreground "#ff6655")) (((class color) (min-colors 16)) (:foreground "red"))))
 '(custom-group-tag ((((class color) (min-colors 257)) (:foreground "#a9a1e1")) (((class color) (min-colors 256)) (:foreground "#a9a1e1")) (((class color) (min-colors 16)) (:foreground "magenta"))))
 '(custom-group-tag-1 ((((class color) (min-colors 257)) (:foreground "#51afef")) (((class color) (min-colors 256)) (:foreground "#51afef")) (((class color) (min-colors 16)) (:foreground "brightblue"))))
 '(custom-set ((((class color) (min-colors 257)) (:foreground "#ECBE7B" :background "#282c34")) (((class color) (min-colors 256)) (:foreground "#ECBE7B" :background "black")) (((class color) (min-colors 16)) (:foreground "yellow" :background "black"))))
 '(custom-themed ((((class color) (min-colors 257)) (:foreground "#ECBE7B" :background "#282c34")) (((class color) (min-colors 256)) (:foreground "#ECBE7B" :background "black")) (((class color) (min-colors 16)) (:foreground "yellow" :background "black"))))
 '(custom-invalid ((((class color) (min-colors 257)) (:foreground "#ff6c6b" :background "#53383f")) (((class color) (min-colors 256)) (:foreground "#ff6655" :background "#ff6655")) (((class color) (min-colors 16)) (:foreground "red" :background "red"))))
 '(custom-variable-obsolete ((((class color) (min-colors 257)) (:foreground "#3f444a" :background "#282c34")) (((class color) (min-colors 256)) (:foreground "#3f3f3f" :background "black")) (((class color) (min-colors 16)) (:foreground "brightblack" :background "black"))))
 '(custom-state ((((class color) (min-colors 257)) (:foreground "#98be65" :background "#3e493d")) (((class color) (min-colors 256)) (:foreground "#99bb66" :background "#99bb66")) (((class color) (min-colors 16)) (:foreground "green" :background "green"))))
 '(custom-changed ((((class color) (min-colors 257)) (:foreground "#51afef" :background "#282c34")) (((class color) (min-colors 256)) (:foreground "#51afef" :background "black")) (((class color) (min-colors 16)) (:foreground "brightblue" :background "black"))))
 '(diff-hl-change ((((class color) (min-colors 257)) (:foreground "#da8548" :background "#da8548")) (((class color) (min-colors 256)) (:foreground "#dd8844" :background "#dd8844")) (((class color) (min-colors 16)) (:foreground "brightred" :background "brightred"))))
 '(diff-hl-delete ((((class color) (min-colors 257)) (:foreground "#ff6c6b" :background "#ff6c6b")) (((class color) (min-colors 256)) (:foreground "#ff6655" :background "#ff6655")) (((class color) (min-colors 16)) (:foreground "red" :background "red"))))
 '(diff-hl-insert ((((class color) (min-colors 257)) (:foreground "#98be65" :background "#98be65")) (((class color) (min-colors 256)) (:foreground "#99bb66" :background "#99bb66")) (((class color) (min-colors 16)) (:foreground "green" :background "green"))))
 '(diff-added ((((class color) (min-colors 257)) (:inherit hl-line :foreground "#98be65")) (((class color) (min-colors 256)) (:inherit hl-line :foreground "#99bb66")) (((class color) (min-colors 16)) (:inherit hl-line :foreground "green"))))
 '(diff-changed ((((class color) (min-colors 257)) (:foreground "#a9a1e1")) (((class color) (min-colors 256)) (:foreground "#a9a1e1")) (((class color) (min-colors 16)) (:foreground "magenta"))))
 '(diff-context ((((class color) (min-colors 257) (background dark)) (:foreground "#a4aab6")) (((class color) (min-colors 256) (background dark)) (:foreground "#a8a8a8")) (((class color) (min-colors 16) (background dark)) (:foreground "brightwhite")) (((class color) (min-colors 257) (background light)) (:foreground "#c3c9d4")) (((class color) (min-colors 256) (background light)) (:foreground "#c6c6c6")) (((class color) (min-colors 16) (background light)) (:foreground "brightwhite"))))
 '(diff-removed ((((class color) (min-colors 257)) (:foreground "#ff6c6b" :background "#23272e")) (((class color) (min-colors 256)) (:foreground "#ff6655" :background "#262626")) (((class color) (min-colors 16)) (:foreground "red" :background "brightblack"))))
 '(diff-header ((((class color) (min-colors 257)) (:foreground "#46D9FF")) (((class color) (min-colors 256)) (:foreground "#46D9FF")) (((class color) (min-colors 16)) (:foreground "brightcyan"))))
 '(diff-file-header ((((class color) (min-colors 257)) (:foreground "#51afef")) (((class color) (min-colors 256)) (:foreground "#51afef")) (((class color) (min-colors 16)) (:foreground "brightblue"))))
 '(diff-hunk-header ((((class color) (min-colors 257)) (:foreground "#a9a1e1")) (((class color) (min-colors 256)) (:foreground "#a9a1e1")) (((class color) (min-colors 16)) (:foreground "magenta"))))
 '(diff-refine-added ((t (:inherit diff-added :inverse-video t))))
 '(diff-refine-changed ((t (:inherit diff-changed :inverse-video t))))
 '(diff-refine-removed ((t (:inherit diff-removed :inverse-video t))))
 '(dired-directory ((((class color) (min-colors 257)) (:foreground "#c678dd")) (((class color) (min-colors 256)) (:foreground "#c678dd")) (((class color) (min-colors 16)) (:foreground "brightmagenta"))))
 '(dired-ignored ((((class color) (min-colors 257)) (:foreground "#5B6268")) (((class color) (min-colors 256)) (:foreground "#525252")) (((class color) (min-colors 16)) (:foreground "brightblack"))))
 '(dired-flagged ((((class color) (min-colors 257)) (:foreground "#ff6c6b")) (((class color) (min-colors 256)) (:foreground "#ff6655")) (((class color) (min-colors 16)) (:foreground "red"))))
 '(dired-header ((((class color) (min-colors 257)) (:foreground "#51afef" :weight bold)) (((class color) (min-colors 256)) (:foreground "#51afef" :weight bold)) (((class color) (min-colors 16)) (:foreground "brightblue" :weight bold))))
 '(dired-mark ((((class color) (min-colors 257)) (:foreground "#da8548" :weight bold)) (((class color) (min-colors 256)) (:foreground "#dd8844" :weight bold)) (((class color) (min-colors 16)) (:foreground "brightred" :weight bold))))
 '(dired-marked ((((class color) (min-colors 257)) (:foreground "#c678dd" :weight bold :inverse-video t)) (((class color) (min-colors 256)) (:foreground "#c678dd" :weight bold :inverse-video t)) (((class color) (min-colors 16)) (:foreground "brightmagenta" :weight bold :inverse-video t))))
 '(dired-perm-write ((((class color) (min-colors 257)) (:foreground "#bbc2cf" :underline t)) (((class color) (min-colors 256)) (:foreground "#bfbfbf" :underline t)) (((class color) (min-colors 16)) (:foreground "brightwhite" :underline t))))
 '(dired-symlink ((((class color) (min-colors 257)) (:foreground "#46D9FF" :weight bold)) (((class color) (min-colors 256)) (:foreground "#46D9FF" :weight bold)) (((class color) (min-colors 16)) (:foreground "brightcyan" :weight bold))))
 '(dired-warning ((((class color) (min-colors 257)) (:foreground "#ECBE7B")) (((class color) (min-colors 256)) (:foreground "#ECBE7B")) (((class color) (min-colors 16)) (:foreground "yellow"))))
 '(ediff-fine-diff-A ((((class color) (min-colors 257)) (:background "#234a7f" :weight bold :extend t)) (((class color) (min-colors 256)) (:background "#2257A0" :weight bold :extend t)) (((class color) (min-colors 16)) (:background "blue" :weight bold :extend t))))
 '(ediff-fine-diff-B ((t (:inherit ediff-fine-diff-A))))
 '(ediff-fine-diff-C ((t (:inherit ediff-fine-diff-A))))
 '(ediff-current-diff-A ((((class color) (min-colors 257)) (:background "#263854" :extend t)) (((class color) (min-colors 256)) (:background "#2257A0" :extend t)) (((class color) (min-colors 16)) (:background "blue" :extend t))))
 '(ediff-current-diff-B ((t (:inherit ediff-current-diff-A))))
 '(ediff-current-diff-C ((t (:inherit ediff-current-diff-A))))
 '(ediff-even-diff-A ((t (:inherit hl-line))))
 '(ediff-even-diff-B ((t (:inherit ediff-even-diff-A))))
 '(ediff-even-diff-C ((t (:inherit ediff-even-diff-A))))
 '(ediff-odd-diff-A ((t (:inherit ediff-even-diff-A))))
 '(ediff-odd-diff-B ((t (:inherit ediff-odd-diff-A))))
 '(ediff-odd-diff-C ((t (:inherit ediff-odd-diff-A))))
 '(eglot-highlight-symbol-face ((t :underline t)))
 '(erc-button ((t (:weight bold :underline t))))
 '(erc-default-face ((t (:inherit default))))
 '(erc-action-face ((t (:weight bold))))
 '(erc-command-indicator-face ((t (:weight bold))))
 '(erc-direct-msg-face ((((class color) (min-colors 257)) (:foreground "#c678dd")) (((class color) (min-colors 256)) (:foreground "#c678dd")) (((class color) (min-colors 16)) (:foreground "brightmagenta"))))
 '(erc-error-face ((t (:inherit error))))
 '(erc-header-line ((((class color) (min-colors 257)) (:background "#1c1e24" :foreground "#51afef")) (((class color) (min-colors 256)) (:background "black" :foreground "#51afef")) (((class color) (min-colors 16)) (:background "black" :foreground "brightblue"))))
 '(erc-input-face ((((class color) (min-colors 257)) (:foreground "#98be65")) (((class color) (min-colors 256)) (:foreground "#99bb66")) (((class color) (min-colors 16)) (:foreground "green"))))
 '(erc-current-nick-face ((((class color) (min-colors 257)) (:foreground "#98be65" :weight bold)) (((class color) (min-colors 256)) (:foreground "#99bb66" :weight bold)) (((class color) (min-colors 16)) (:foreground "green" :weight bold))))
 '(erc-timestamp-face ((((class color) (min-colors 257)) (:foreground "#51afef" :weight bold)) (((class color) (min-colors 256)) (:foreground "#51afef" :weight bold)) (((class color) (min-colors 16)) (:foreground "brightblue" :weight bold))))
 '(erc-nick-default-face ((t (:weight bold))))
 '(erc-nick-msg-face ((((class color) (min-colors 257)) (:foreground "#c678dd")) (((class color) (min-colors 256)) (:foreground "#c678dd")) (((class color) (min-colors 16)) (:foreground "brightmagenta"))))
 '(erc-nick-prefix-face ((t (:inherit erc-nick-default-face))))
 '(erc-my-nick-face ((((class color) (min-colors 257)) (:foreground "#98be65" :weight bold)) (((class color) (min-colors 256)) (:foreground "#99bb66" :weight bold)) (((class color) (min-colors 16)) (:foreground "green" :weight bold))))
 '(erc-my-nick-prefix-face ((t (:inherit erc-my-nick-face))))
 '(erc-notice-face ((((class color) (min-colors 257)) (:foreground "#5B6268")) (((class color) (min-colors 256)) (:foreground "#525252")) (((class color) (min-colors 16)) (:foreground "brightblack"))))
 '(erc-prompt-face ((((class color) (min-colors 257)) (:foreground "#51afef" :weight bold)) (((class color) (min-colors 256)) (:foreground "#51afef" :weight bold)) (((class color) (min-colors 16)) (:foreground "brightblue" :weight bold))))
 '(eshell-prompt ((((class color) (min-colors 257)) (:foreground "#51afef" :weight bold)) (((class color) (min-colors 256)) (:foreground "#51afef" :weight bold)) (((class color) (min-colors 16)) (:foreground "brightblue" :weight bold))))
 '(eshell-ls-archive ((((class color) (min-colors 257)) (:foreground "#c678dd")) (((class color) (min-colors 256)) (:foreground "#c678dd")) (((class color) (min-colors 16)) (:foreground "brightmagenta"))))
 '(eshell-ls-backup ((((class color) (min-colors 257)) (:foreground "#ECBE7B")) (((class color) (min-colors 256)) (:foreground "#ECBE7B")) (((class color) (min-colors 16)) (:foreground "yellow"))))
 '(eshell-ls-clutter ((((class color) (min-colors 257)) (:foreground "#ff6c6b")) (((class color) (min-colors 256)) (:foreground "#ff6655")) (((class color) (min-colors 16)) (:foreground "red"))))
 '(eshell-ls-directory ((((class color) (min-colors 257)) (:foreground "#51afef")) (((class color) (min-colors 256)) (:foreground "#51afef")) (((class color) (min-colors 16)) (:foreground "brightblue"))))
 '(eshell-ls-executable ((((class color) (min-colors 257)) (:foreground "#98be65")) (((class color) (min-colors 256)) (:foreground "#99bb66")) (((class color) (min-colors 16)) (:foreground "green"))))
 '(eshell-ls-missing ((((class color) (min-colors 257)) (:foreground "#ff6c6b")) (((class color) (min-colors 256)) (:foreground "#ff6655")) (((class color) (min-colors 16)) (:foreground "red"))))
 '(eshell-ls-product ((((class color) (min-colors 257)) (:foreground "#da8548")) (((class color) (min-colors 256)) (:foreground "#dd8844")) (((class color) (min-colors 16)) (:foreground "brightred"))))
 '(eshell-ls-readonly ((((class color) (min-colors 257)) (:foreground "#da8548")) (((class color) (min-colors 256)) (:foreground "#dd8844")) (((class color) (min-colors 16)) (:foreground "brightred"))))
 '(eshell-ls-special ((((class color) (min-colors 257)) (:foreground "#a9a1e1")) (((class color) (min-colors 256)) (:foreground "#a9a1e1")) (((class color) (min-colors 16)) (:foreground "magenta"))))
 '(eshell-ls-symlink ((((class color) (min-colors 257)) (:foreground "#46D9FF")) (((class color) (min-colors 256)) (:foreground "#46D9FF")) (((class color) (min-colors 16)) (:foreground "brightcyan"))))
 '(eshell-ls-unreadable ((((class color) (min-colors 257)) (:foreground "#5B6268")) (((class color) (min-colors 256)) (:foreground "#525252")) (((class color) (min-colors 16)) (:foreground "brightblack"))))
 '(eww-form-checkbox ((t (:inherit eww-form-file))))
 '(eww-form-file ((((class color) (min-colors 257)) (:inherit eww-form-submit :background "#21242b")) (((class color) (min-colors 256)) (:inherit eww-form-submit :background "black")) (((class color) (min-colors 16)) (:inherit eww-form-submit :background "black"))))
 '(eww-form-select ((((class color) (min-colors 257)) (:inherit eww-form-submit :background "#21242b")) (((class color) (min-colors 256)) (:inherit eww-form-submit :background "black")) (((class color) (min-colors 16)) (:inherit eww-form-submit :background "black"))))
 '(eww-form-submit ((((class color) (min-colors 257)) (:inherit eww-form-text :box (:line-width 2 :style released-button) :background "#202328")) (((class color) (min-colors 256)) (:inherit eww-form-text :box (:line-width 2 :style released-button) :background "#2e2e2e")) (((class color) (min-colors 16)) (:inherit eww-form-text :box (:line-width 2 :style released-button) :background "brightblack"))))
 '(eww-form-text ((((class color) (min-colors 257)) (:box (:line-width 1 :color "#23272e") :background "#282c34" :foreground "#bbc2cf" :distant-foreground "#282c34")) (((class color) (min-colors 256)) (:box (:line-width 1 :color "#262626") :background "black" :foreground "#bfbfbf" :distant-foreground "black")) (((class color) (min-colors 16)) (:box (:line-width 1 :color "brightblack") :background "black" :foreground "brightwhite" :distant-foreground "black"))))
 '(eww-form-textarea ((t (:inherit eww-form-text))))
 '(eww-invalid-certificate ((((class color) (min-colors 257)) (:foreground "#ff6c6b")) (((class color) (min-colors 256)) (:foreground "#ff6655")) (((class color) (min-colors 16)) (:foreground "red"))))
 '(eww-valid-certificate ((((class color) (min-colors 257)) (:foreground "#51afef")) (((class color) (min-colors 256)) (:foreground "#51afef")) (((class color) (min-colors 16)) (:foreground "brightblue"))))
 '(flymake-error ((((class color) (min-colors 257)) (:underline (:style wave :color "#ff6c6b"))) (((class color) (min-colors 256)) (:underline (:style wave :color "#ff6655"))) (((class color) (min-colors 16)) (:underline (:style wave :color "red")))))
 '(flymake-note ((((class color) (min-colors 257)) (:underline (:style wave :color "#98be65"))) (((class color) (min-colors 256)) (:underline (:style wave :color "#99bb66"))) (((class color) (min-colors 16)) (:underline (:style wave :color "green")))))
 '(flymake-warning ((((class color) (min-colors 257)) (:underline (:style wave :color "#da8548"))) (((class color) (min-colors 256)) (:underline (:style wave :color "#dd8844"))) (((class color) (min-colors 16)) (:underline (:style wave :color "brightred")))))
 '(flyspell-incorrect ((((class color) (min-colors 257)) (:underline (:style wave :color "#ff6c6b") :inherit unspecified)) (((class color) (min-colors 256)) (:underline (:style wave :color "#ff6655") :inherit unspecified)) (((class color) (min-colors 16)) (:underline (:style wave :color "red") :inherit unspecified))))
 '(flyspell-duplicate ((((class color) (min-colors 257)) (:underline (:style wave :color "#ECBE7B") :inherit unspecified)) (((class color) (min-colors 256)) (:underline (:style wave :color "#ECBE7B") :inherit unspecified)) (((class color) (min-colors 16)) (:underline (:style wave :color "yellow") :inherit unspecified))))
 '(gnus-group-mail-1 ((((class color) (min-colors 257)) (:weight bold :foreground "#bbc2cf")) (((class color) (min-colors 256)) (:weight bold :foreground "#bfbfbf")) (((class color) (min-colors 16)) (:weight bold :foreground "brightwhite"))))
 '(gnus-group-mail-2 ((t (:inherit gnus-group-mail-1))))
 '(gnus-group-mail-3 ((t (:inherit gnus-group-mail-1))))
 '(gnus-group-mail-1-empty ((((class color) (min-colors 257)) (:foreground "#5B6268")) (((class color) (min-colors 256)) (:foreground "#525252")) (((class color) (min-colors 16)) (:foreground "brightblack"))))
 '(gnus-group-mail-2-empty ((t (:inherit gnus-group-mail-1-empty))))
 '(gnus-group-mail-3-empty ((t (:inherit gnus-group-mail-1-empty))))
 '(gnus-group-news-1 ((t (:inherit gnus-group-mail-1))))
 '(gnus-group-news-2 ((t (:inherit gnus-group-news-1))))
 '(gnus-group-news-3 ((t (:inherit gnus-group-news-1))))
 '(gnus-group-news-4 ((t (:inherit gnus-group-news-1))))
 '(gnus-group-news-5 ((t (:inherit gnus-group-news-1))))
 '(gnus-group-news-6 ((t (:inherit gnus-group-news-1))))
 '(gnus-group-news-1-empty ((t (:inherit gnus-group-mail-1-empty))))
 '(gnus-group-news-2-empty ((t (:inherit gnus-group-news-1-empty))))
 '(gnus-group-news-3-empty ((t (:inherit gnus-group-news-1-empty))))
 '(gnus-group-news-4-empty ((t (:inherit gnus-group-news-1-empty))))
 '(gnus-group-news-5-empty ((t (:inherit gnus-group-news-1-empty))))
 '(gnus-group-news-6-empty ((t (:inherit gnus-group-news-1-empty))))
 '(gnus-group-mail-low ((t (:inherit gnus-group-mail-1 :weight normal))))
 '(gnus-group-mail-low-empty ((t (:inherit gnus-group-mail-1-empty))))
 '(gnus-group-news-low ((((class color) (min-colors 257)) (:inherit gnus-group-mail-1 :foreground "#5B6268")) (((class color) (min-colors 256)) (:inherit gnus-group-mail-1 :foreground "#525252")) (((class color) (min-colors 16)) (:inherit gnus-group-mail-1 :foreground "brightblack"))))
 '(gnus-group-news-low-empty ((t (:inherit gnus-group-news-low :weight normal))))
 '(gnus-header-content ((t (:inherit font-lock-constant-face))))
 '(gnus-header-from ((t (:inherit error))))
 '(gnus-header-name ((t (:inherit success))))
 '(gnus-header-newsgroups ((t (:inherit success))))
 '(gnus-header-subject ((t (:inherit font-lock-type-face))))
 '(gnus-summary-cancelled ((((class color) (min-colors 257)) (:foreground "#ff6c6b" :strike-through t)) (((class color) (min-colors 256)) (:foreground "#ff6655" :strike-through t)) (((class color) (min-colors 16)) (:foreground "red" :strike-through t))))
 '(gnus-summary-high-ancient ((((class color) (min-colors 257)) (:foreground "#7b8186" :inherit italic)) (((class color) (min-colors 256)) (:foreground "#747474" :inherit italic)) (((class color) (min-colors 16)) (:foreground "brightblack" :inherit italic))))
 '(gnus-summary-high-read ((((class color) (min-colors 257)) (:foreground "#c8ced8")) (((class color) (min-colors 256)) (:foreground "#cbcbcb")) (((class color) (min-colors 16)) (:foreground "brightwhite"))))
 '(gnus-summary-high-ticked ((((class color) (min-colors 257)) (:foreground "#d193e3")) (((class color) (min-colors 256)) (:foreground "#d193e3")) (((class color) (min-colors 16)) (:foreground "brightmagenta"))))
 '(gnus-summary-high-unread ((((class color) (min-colors 257)) (:foreground "#accb83")) (((class color) (min-colors 256)) (:foreground "#adc884")) (((class color) (min-colors 16)) (:foreground "green"))))
 '(gnus-summary-low-ancient ((((class color) (min-colors 257)) (:foreground "#484e53" :inherit italic)) (((class color) (min-colors 256)) (:foreground "#414141" :inherit italic)) (((class color) (min-colors 16)) (:foreground "brightblack" :inherit italic))))
 '(gnus-summary-low-read ((((class color) (min-colors 257)) (:foreground "#959ba5")) (((class color) (min-colors 256)) (:foreground "#989898")) (((class color) (min-colors 16)) (:foreground "brightwhite"))))
 '(gnus-summary-low-ticked ((((class color) (min-colors 257)) (:foreground "#9e60b0")) (((class color) (min-colors 256)) (:foreground "#9e60b0")) (((class color) (min-colors 16)) (:foreground "brightmagenta"))))
 '(gnus-summary-low-unread ((((class color) (min-colors 257)) (:foreground "#799850")) (((class color) (min-colors 256)) (:foreground "#7a9551")) (((class color) (min-colors 16)) (:foreground "green"))))
 '(gnus-summary-normal-ancient ((((class color) (min-colors 257)) (:foreground "#5B6268" :inherit italic)) (((class color) (min-colors 256)) (:foreground "#525252" :inherit italic)) (((class color) (min-colors 16)) (:foreground "brightblack" :inherit italic))))
 '(gnus-summary-normal-read ((((class color) (min-colors 257)) (:foreground "#bbc2cf")) (((class color) (min-colors 256)) (:foreground "#bfbfbf")) (((class color) (min-colors 16)) (:foreground "brightwhite"))))
 '(gnus-summary-normal-ticked ((((class color) (min-colors 257)) (:foreground "#c678dd")) (((class color) (min-colors 256)) (:foreground "#c678dd")) (((class color) (min-colors 16)) (:foreground "brightmagenta"))))
 '(gnus-summary-normal-unread ((((class color) (min-colors 257)) (:foreground "#98be65" :inherit bold)) (((class color) (min-colors 256)) (:foreground "#99bb66" :inherit bold)) (((class color) (min-colors 16)) (:foreground "green" :inherit bold))))
 '(gnus-summary-selected ((((class color) (min-colors 257)) (:foreground "#51afef" :weight bold)) (((class color) (min-colors 256)) (:foreground "#51afef" :weight bold)) (((class color) (min-colors 16)) (:foreground "brightblue" :weight bold))))
 '(gnus-cite-1 ((((class color) (min-colors 257)) (:foreground "#a9a1e1")) (((class color) (min-colors 256)) (:foreground "#a9a1e1")) (((class color) (min-colors 16)) (:foreground "magenta"))))
 '(gnus-cite-2 ((((class color) (min-colors 257)) (:foreground "#ECBE7B")) (((class color) (min-colors 256)) (:foreground "#ECBE7B")) (((class color) (min-colors 16)) (:foreground "yellow"))))
 '(gnus-cite-3 ((((class color) (min-colors 257)) (:foreground "#c678dd")) (((class color) (min-colors 256)) (:foreground "#c678dd")) (((class color) (min-colors 16)) (:foreground "brightmagenta"))))
 '(gnus-cite-4 ((((class color) (min-colors 257)) (:foreground "#98be65")) (((class color) (min-colors 256)) (:foreground "#99bb66")) (((class color) (min-colors 16)) (:foreground "green"))))
 '(gnus-cite-5 ((((class color) (min-colors 257)) (:foreground "#98be65")) (((class color) (min-colors 256)) (:foreground "#99bb66")) (((class color) (min-colors 16)) (:foreground "green"))))
 '(gnus-cite-6 ((((class color) (min-colors 257)) (:foreground "#98be65")) (((class color) (min-colors 256)) (:foreground "#99bb66")) (((class color) (min-colors 16)) (:foreground "green"))))
 '(gnus-cite-7 ((((class color) (min-colors 257)) (:foreground "#c678dd")) (((class color) (min-colors 256)) (:foreground "#c678dd")) (((class color) (min-colors 16)) (:foreground "brightmagenta"))))
 '(gnus-cite-8 ((((class color) (min-colors 257)) (:foreground "#c678dd")) (((class color) (min-colors 256)) (:foreground "#c678dd")) (((class color) (min-colors 16)) (:foreground "brightmagenta"))))
 '(gnus-cite-9 ((((class color) (min-colors 257)) (:foreground "#c678dd")) (((class color) (min-colors 256)) (:foreground "#c678dd")) (((class color) (min-colors 16)) (:foreground "brightmagenta"))))
 '(gnus-cite-10 ((((class color) (min-colors 257)) (:foreground "#ECBE7B")) (((class color) (min-colors 256)) (:foreground "#ECBE7B")) (((class color) (min-colors 16)) (:foreground "yellow"))))
 '(gnus-cite-11 ((((class color) (min-colors 257)) (:foreground "#ECBE7B")) (((class color) (min-colors 256)) (:foreground "#ECBE7B")) (((class color) (min-colors 16)) (:foreground "yellow"))))
 '(gnus-signature ((((class color) (min-colors 257)) (:foreground "#ECBE7B")) (((class color) (min-colors 256)) (:foreground "#ECBE7B")) (((class color) (min-colors 16)) (:foreground "yellow"))))
 '(gnus-x-face ((((class color) (min-colors 257)) (:background "#5B6268" :foreground "#bbc2cf")) (((class color) (min-colors 256)) (:background "#525252" :foreground "#bfbfbf")) (((class color) (min-colors 16)) (:background "brightblack" :foreground "brightwhite"))))
 '(highlight-numbers-number ((((class color) (min-colors 257)) (:inherit bold :foreground "#da8548")) (((class color) (min-colors 256)) (:inherit bold :foreground "#dd8844")) (((class color) (min-colors 16)) (:inherit bold :foreground "brightred"))))
 '(highlight-indentation-face ((t (:inherit hl-line))))
 '(highlight-indentation-current-column-face ((((class color) (min-colors 257)) (:background "#1c1f24")) (((class color) (min-colors 256)) (:background "#1e1e1e")) (((class color) (min-colors 16)) (:background "brightblack"))))
 '(highlight-indentation-guides-odd-face ((t (:inherit highlight-indentation-face))))
 '(highlight-indentation-guides-even-face ((t (:inherit highlight-indentation-face))))
 '(highlight-quoted-symbol ((((class color) (min-colors 257)) (:foreground "#ECBE7B")) (((class color) (min-colors 256)) (:foreground "#ECBE7B")) (((class color) (min-colors 16)) (:foreground "yellow"))))
 '(highlight-quoted-quote ((((class color) (min-colors 257)) (:foreground "#51afef")) (((class color) (min-colors 256)) (:foreground "#51afef")) (((class color) (min-colors 16)) (:foreground "brightblue"))))
 '(highlight-symbol-face ((((class color) (min-colors 257) (background dark)) (:background "#54565c" :distant-foreground "#5B6268")) (((class color) (min-colors 256) (background dark)) (:background "#7a7a7a" :distant-foreground "#2d2d2d")) (((class color) (min-colors 16) (background dark)) (:background "brightblack" :distant-foreground "white")) (((class color) (min-colors 257) (background light)) (:background "#3b3d42" :distant-foreground "#5B6268")) (((class color) (min-colors 256) (background light)) (:background "#616161" :distant-foreground "#2d2d2d")) (((class color) (min-colors 16) (background light)) (:background "brightblack" :distant-foreground "white"))))
 '(highlight-thing ((((class color) (min-colors 257) (background dark)) (:background "#54565c" :distant-foreground "#5B6268")) (((class color) (min-colors 256) (background dark)) (:background "#7a7a7a" :distant-foreground "#2d2d2d")) (((class color) (min-colors 16) (background dark)) (:background "brightblack" :distant-foreground "white")) (((class color) (min-colors 257) (background light)) (:background "#3b3d42" :distant-foreground "#5B6268")) (((class color) (min-colors 256) (background light)) (:background "#616161" :distant-foreground "#2d2d2d")) (((class color) (min-colors 16) (background light)) (:background "brightblack" :distant-foreground "white"))))
 '(hl-fill-column-face ((t (:inherit (hl-line shadow)))))
 '(hl-line ((((class color) (min-colors 257)) (:background "#21242b" :extend t)) (((class color) (min-colors 256)) (:background "black" :extend t)) (((class color) (min-colors 16)) (:background "black" :extend t))))
 '(hl-todo ((((class color) (min-colors 257)) (:foreground "#ff6c6b" :weight bold)) (((class color) (min-colors 256)) (:foreground "#ff6655" :weight bold)) (((class color) (min-colors 16)) (:foreground "red" :weight bold))))
 '(ido-first-match ((((class color) (min-colors 257)) (:foreground "#da8548")) (((class color) (min-colors 256)) (:foreground "#dd8844")) (((class color) (min-colors 16)) (:foreground "brightred"))))
 '(ido-indicator ((((class color) (min-colors 257)) (:foreground "#ff6c6b" :background "#282c34")) (((class color) (min-colors 256)) (:foreground "#ff6655" :background "black")) (((class color) (min-colors 16)) (:foreground "red" :background "black"))))
 '(ido-only-match ((((class color) (min-colors 257)) (:foreground "#98be65")) (((class color) (min-colors 256)) (:foreground "#99bb66")) (((class color) (min-colors 16)) (:foreground "green"))))
 '(ido-subdir ((((class color) (min-colors 257)) (:foreground "#a9a1e1")) (((class color) (min-colors 256)) (:foreground "#a9a1e1")) (((class color) (min-colors 16)) (:foreground "magenta"))))
 '(ido-virtual ((((class color) (min-colors 257)) (:foreground "#5B6268")) (((class color) (min-colors 256)) (:foreground "#525252")) (((class color) (min-colors 16)) (:foreground "brightblack"))))
 '(imenu-list-entry-face-0 ((((class color) (min-colors 257)) (:foreground "#51afef")) (((class color) (min-colors 256)) (:foreground "#51afef")) (((class color) (min-colors 16)) (:foreground "brightblue"))))
 '(imenu-list-entry-subalist-face-0 ((t (:inherit imenu-list-entry-face-0 :weight bold))))
 '(imenu-list-entry-face-1 ((((class color) (min-colors 257)) (:foreground "#98be65")) (((class color) (min-colors 256)) (:foreground "#99bb66")) (((class color) (min-colors 16)) (:foreground "green"))))
 '(imenu-list-entry-subalist-face-1 ((t (:inherit imenu-list-entry-face-1 :weight bold))))
 '(imenu-list-entry-face-2 ((((class color) (min-colors 257)) (:foreground "#ECBE7B")) (((class color) (min-colors 256)) (:foreground "#ECBE7B")) (((class color) (min-colors 16)) (:foreground "yellow"))))
 '(imenu-list-entry-subalist-face-2 ((t (:inherit imenu-list-entry-face-2 :weight bold))))
 '(isearch ((t (:inherit lazy-highlight :weight bold))))
 '(isearch-fail ((((class color) (min-colors 257)) (:background "#ff6c6b" :foreground "#1B2229" :weight bold)) (((class color) (min-colors 256)) (:background "#ff6655" :foreground "black" :weight bold)) (((class color) (min-colors 16)) (:background "red" :foreground "black" :weight bold))))
 '(paren-face-match ((((class color) (min-colors 257)) (:foreground "#ff6c6b" :background "#1B2229" :weight ultra-bold)) (((class color) (min-colors 256)) (:foreground "#ff6655" :background "black" :weight ultra-bold)) (((class color) (min-colors 16)) (:foreground "red" :background "black" :weight ultra-bold))))
 '(paren-face-mismatch ((((class color) (min-colors 257)) (:foreground "#1B2229" :background "#ff6c6b" :weight ultra-bold)) (((class color) (min-colors 256)) (:foreground "black" :background "#ff6655" :weight ultra-bold)) (((class color) (min-colors 16)) (:foreground "black" :background "red" :weight ultra-bold))))
 '(paren-face-no-match ((t (:inherit paren-face-mismatch :weight ultra-bold))))
 '(org-archived ((((class color) (min-colors 257)) (:foreground "#83898d")) (((class color) (min-colors 256)) (:foreground "#7d7d7d")) (((class color) (min-colors 16)) (:foreground "brightblack"))))
 '(org-block ((((class color) (min-colors 257)) (:background "#23272e" :extend t)) (((class color) (min-colors 256)) (:background "#262626" :extend t)) (((class color) (min-colors 16)) (:background "brightblack" :extend t))))
 '(org-block-background ((((class color) (min-colors 257)) (:background "#23272e" :extend t)) (((class color) (min-colors 256)) (:background "#262626" :extend t)) (((class color) (min-colors 16)) (:background "brightblack" :extend t))))
 '(org-block-begin-line ((((class color) (min-colors 257)) (:inherit org-block :foreground "#5B6268")) (((class color) (min-colors 256)) (:inherit org-block :foreground "#525252")) (((class color) (min-colors 16)) (:inherit org-block :foreground "brightblack"))))
 '(org-block-end-line ((t (:inherit org-block-begin-line))))
 '(org-checkbox ((t (:inherit org-todo))))
 '(org-checkbox-statistics-done ((t (:inherit org-done))))
 '(org-checkbox-statistics-todo ((t (:inherit org-todo))))
 '(org-cite ((((class color) (min-colors 257)) (:foreground "#57b6be")) (((class color) (min-colors 256)) (:foreground "#50b9b2")) (((class color) (min-colors 16)) (:foreground "brightgreen"))))
 '(org-cite-key ((((class color) (min-colors 257)) (:foreground "#79bac4" :underline t)) (((class color) (min-colors 256)) (:foreground "#75bbb6" :underline t)) (((class color) (min-colors 16)) (:foreground "brightgreen" :underline t))))
 '(org-code ((((class color) (min-colors 257)) (:inherit org-block :foreground "#da8548")) (((class color) (min-colors 256)) (:inherit org-block :foreground "#dd8844")) (((class color) (min-colors 16)) (:inherit org-block :foreground "brightred"))))
 '(org-date ((((class color) (min-colors 257)) (:foreground "#ECBE7B")) (((class color) (min-colors 256)) (:foreground "#ECBE7B")) (((class color) (min-colors 16)) (:foreground "yellow"))))
 '(org-default ((t (:inherit variable-pitch))))
 '(org-document-info ((((class color) (min-colors 257)) (:foreground "#c678dd")) (((class color) (min-colors 256)) (:foreground "#c678dd")) (((class color) (min-colors 16)) (:foreground "brightmagenta"))))
 '(org-document-title ((((class color) (min-colors 257)) (:foreground "#c678dd" :weight bold)) (((class color) (min-colors 256)) (:foreground "#c678dd" :weight bold)) (((class color) (min-colors 16)) (:foreground "brightmagenta" :weight bold))))
 '(org-done ((t (:inherit org-headline-done :strike-through nil :weight bold))))
 '(org-drawer ((((class color) (min-colors 257)) (:foreground "#5B6268")) (((class color) (min-colors 256)) (:foreground "#525252")) (((class color) (min-colors 16)) (:foreground "brightblack"))))
 '(org-ellipsis ((((class color) (min-colors 257)) (:foreground "#5B6268" :underline nil)) (((class color) (min-colors 256)) (:foreground "#525252" :underline nil)) (((class color) (min-colors 16)) (:foreground "brightblack" :underline nil))))
 '(org-footnote ((((class color) (min-colors 257)) (:foreground "#da8548")) (((class color) (min-colors 256)) (:foreground "#dd8844")) (((class color) (min-colors 16)) (:foreground "brightred"))))
 '(org-formula ((((class color) (min-colors 257)) (:foreground "#46D9FF")) (((class color) (min-colors 256)) (:foreground "#46D9FF")) (((class color) (min-colors 16)) (:foreground "brightcyan"))))
 '(org-headline-done ((((class color) (min-colors 257)) (:foreground "#5B6268")) (((class color) (min-colors 256)) (:foreground "#525252")) (((class color) (min-colors 16)) (:foreground "brightblack"))))
 '(org-hide ((((class color) (min-colors 257)) (:foreground "#282c34")) (((class color) (min-colors 256)) (:foreground "black")) (((class color) (min-colors 16)) (:foreground "black"))))
 '(org-latex-and-related ((((class color) (min-colors 257)) (:foreground "#DFDFDF" :weight bold)) (((class color) (min-colors 256)) (:foreground "#dfdfdf" :weight bold)) (((class color) (min-colors 16)) (:foreground "white" :weight bold))))
 '(org-link ((((class color) (min-colors 257)) (:inherit link :foreground "#51afef")) (((class color) (min-colors 256)) (:inherit link :foreground "#51afef")) (((class color) (min-colors 16)) (:inherit link :foreground "brightblue"))))
 '(org-list-dt ((((class color) (min-colors 257)) (:foreground "#51afef")) (((class color) (min-colors 256)) (:foreground "#51afef")) (((class color) (min-colors 16)) (:foreground "brightblue"))))
 '(org-meta-line ((((class color) (min-colors 257)) (:foreground "#83898d")) (((class color) (min-colors 256)) (:foreground "#7d7d7d")) (((class color) (min-colors 16)) (:foreground "brightblack"))))
 '(org-priority ((((class color) (min-colors 257)) (:foreground "#ff6c6b")) (((class color) (min-colors 256)) (:foreground "#ff6655")) (((class color) (min-colors 16)) (:foreground "red"))))
 '(org-property-value ((((class color) (min-colors 257)) (:foreground "#83898d")) (((class color) (min-colors 256)) (:foreground "#7d7d7d")) (((class color) (min-colors 16)) (:foreground "brightblack"))))
 '(org-quote ((t (:inherit org-block :slant italic))))
 '(org-special-keyword ((((class color) (min-colors 257)) (:foreground "#83898d")) (((class color) (min-colors 256)) (:foreground "#7d7d7d")) (((class color) (min-colors 16)) (:foreground "brightblack"))))
 '(org-table ((((class color) (min-colors 257)) (:foreground "#a9a1e1")) (((class color) (min-colors 256)) (:foreground "#a9a1e1")) (((class color) (min-colors 16)) (:foreground "magenta"))))
 '(org-tag ((((class color) (min-colors 257)) (:foreground "#83898d" :weight normal)) (((class color) (min-colors 256)) (:foreground "#7d7d7d" :weight normal)) (((class color) (min-colors 16)) (:foreground "brightblack" :weight normal))))
 '(org-todo ((((class color) (min-colors 257)) (:foreground "#98be65" :bold inherit)) (((class color) (min-colors 256)) (:foreground "#99bb66" :bold inherit)) (((class color) (min-colors 16)) (:foreground "green" :bold inherit))))
 '(org-verbatim ((((class color) (min-colors 257)) (:foreground "#98be65")) (((class color) (min-colors 256)) (:foreground "#99bb66")) (((class color) (min-colors 16)) (:foreground "green"))))
 '(org-warning ((((class color) (min-colors 257)) (:foreground "#ECBE7B")) (((class color) (min-colors 256)) (:foreground "#ECBE7B")) (((class color) (min-colors 16)) (:foreground "yellow"))))
 '(org-ref-acronym-face ((((class color) (min-colors 257)) (:foreground "#a9a1e1")) (((class color) (min-colors 256)) (:foreground "#a9a1e1")) (((class color) (min-colors 16)) (:foreground "magenta"))))
 '(org-ref-cite-face ((((class color) (min-colors 257)) (:foreground "#ECBE7B" :weight light :underline t)) (((class color) (min-colors 256)) (:foreground "#ECBE7B" :weight light :underline t)) (((class color) (min-colors 16)) (:foreground "yellow" :weight light :underline t))))
 '(org-ref-glossary-face ((((class color) (min-colors 257)) (:foreground "#c678dd")) (((class color) (min-colors 256)) (:foreground "#c678dd")) (((class color) (min-colors 16)) (:foreground "brightmagenta"))))
 '(org-ref-label-face ((((class color) (min-colors 257)) (:foreground "#51afef")) (((class color) (min-colors 256)) (:foreground "#51afef")) (((class color) (min-colors 16)) (:foreground "brightblue"))))
 '(org-ref-ref-face ((((class color) (min-colors 257)) (:inherit link :foreground "#4db5bd")) (((class color) (min-colors 256)) (:inherit link :foreground "#44b9b1")) (((class color) (min-colors 16)) (:inherit link :foreground "brightgreen"))))
 '(outline-1 ((((class color) (min-colors 257)) (:foreground "#51afef" :weight bold :extend t)) (((class color) (min-colors 256)) (:foreground "#51afef" :weight bold :extend t)) (((class color) (min-colors 16)) (:foreground "brightblue" :weight bold :extend t))))
 '(outline-2 ((((class color) (min-colors 257)) (:foreground "#c678dd" :weight bold :extend t)) (((class color) (min-colors 256)) (:foreground "#c678dd" :weight bold :extend t)) (((class color) (min-colors 16)) (:foreground "brightmagenta" :weight bold :extend t))))
 '(outline-3 ((((class color) (min-colors 257)) (:foreground "#a9a1e1" :weight bold :extend t)) (((class color) (min-colors 256)) (:foreground "#a9a1e1" :weight bold :extend t)) (((class color) (min-colors 16)) (:foreground "magenta" :weight bold :extend t))))
 '(outline-4 ((((class color) (min-colors 257)) (:foreground "#7cc3f3" :weight bold :extend t)) (((class color) (min-colors 256)) (:foreground "#7cc3f3" :weight bold :extend t)) (((class color) (min-colors 16)) (:foreground "brightblue" :weight bold :extend t))))
 '(outline-5 ((((class color) (min-colors 257)) (:foreground "#d499e5" :weight bold :extend t)) (((class color) (min-colors 256)) (:foreground "#d499e5" :weight bold :extend t)) (((class color) (min-colors 16)) (:foreground "brightmagenta" :weight bold :extend t))))
 '(outline-6 ((((class color) (min-colors 257)) (:foreground "#a8d7f7" :weight bold :extend t)) (((class color) (min-colors 256)) (:foreground "#a8d7f7" :weight bold :extend t)) (((class color) (min-colors 16)) (:foreground "brightblue" :weight bold :extend t))))
 '(outline-7 ((((class color) (min-colors 257)) (:foreground "#e2bbee" :weight bold :extend t)) (((class color) (min-colors 256)) (:foreground "#e2bbee" :weight bold :extend t)) (((class color) (min-colors 16)) (:foreground "brightmagenta" :weight bold :extend t))))
 '(outline-8 ((((class color) (min-colors 257)) (:foreground "#dceffb" :weight bold :extend t)) (((class color) (min-colors 256)) (:foreground "#dceffb" :weight bold :extend t)) (((class color) (min-colors 16)) (:foreground "brightblue" :weight bold :extend t))))
 '(paren-face ((((class color) (min-colors 257)) (:foreground "#5B6268")) (((class color) (min-colors 256)) (:foreground "#525252")) (((class color) (min-colors 16)) (:foreground "brightblack"))))
 '(rst-block ((t (:inherit font-lock-constant-face))))
 '(rst-level-1 ((t (:inherit rst-adornment :weight bold))))
 '(rst-level-2 ((t (:inherit rst-adornment :weight bold))))
 '(rst-level-3 ((t (:inherit rst-adornment :weight bold))))
 '(rst-level-4 ((t (:inherit rst-adornment :weight bold))))
 '(rst-level-5 ((t (:inherit rst-adornment :weight bold))))
 '(rst-level-6 ((t (:inherit rst-adornment :weight bold))))
 '(message-cited-text ((((class color) (min-colors 257)) (:foreground "#a9a1e1")) (((class color) (min-colors 256)) (:foreground "#a9a1e1")) (((class color) (min-colors 16)) (:foreground "magenta"))))
 '(message-cited-text-1 ((((class color) (min-colors 257)) (:foreground "#ECBE7B")) (((class color) (min-colors 256)) (:foreground "#ECBE7B")) (((class color) (min-colors 16)) (:foreground "yellow"))))
 '(message-cited-text-2 ((((class color) (min-colors 257)) (:foreground "#c678dd")) (((class color) (min-colors 256)) (:foreground "#c678dd")) (((class color) (min-colors 16)) (:foreground "brightmagenta"))))
 '(message-cited-text-3 ((((class color) (min-colors 257)) (:foreground "#98be65")) (((class color) (min-colors 256)) (:foreground "#99bb66")) (((class color) (min-colors 16)) (:foreground "green"))))
 '(message-cited-text-4 ((((class color) (min-colors 257)) (:foreground "#98be65")) (((class color) (min-colors 256)) (:foreground "#99bb66")) (((class color) (min-colors 16)) (:foreground "green"))))
 '(show-paren-match ((((class color) (min-colors 257)) (:foreground "#ff6c6b" :background "#1B2229" :weight ultra-bold)) (((class color) (min-colors 256)) (:foreground "#ff6655" :background "black" :weight ultra-bold)) (((class color) (min-colors 16)) (:foreground "red" :background "black" :weight ultra-bold))))
 '(show-paren-mismatch ((((class color) (min-colors 257)) (:foreground "#1B2229" :background "#ff6c6b" :weight ultra-bold)) (((class color) (min-colors 256)) (:foreground "black" :background "#ff6655" :weight ultra-bold)) (((class color) (min-colors 16)) (:foreground "black" :background "red" :weight ultra-bold))))
 '(xref-file-header ((t (:inherit success))))
 '(xref-line-number ((((class color) (min-colors 257)) (:foreground "#51afef")) (((class color) (min-colors 256)) (:foreground "#51afef")) (((class color) (min-colors 16)) (:foreground "brightblue"))))
 '(xref-match ((t (:background "#1B2229" :foreground "#98be65" :weight bold))))
 '(default ((t (:background "#282c34" :foreground "#bbc2cf"))))
 '(widget-field ((t (:extend t :background "#1b2229" :box (:line-width (1 . -1) :color "#1b2229")))))
 '(widget-single-line-field ((t (:background "#1b2229")))))

(provide-theme 'watson)
